insert into authors (name, biography) values ('Drucie Goodbourn', NULL);
insert into authors (name, biography) values ('Marcia Aggiss', NULL);
insert into authors (name, biography) values ('Giovanni Bigg', NULL);
insert into authors (name, biography) values ('Duffie Eynon', NULL);
insert into authors (name, biography) values ('Anselma McKennan', NULL);
insert into authors (name, biography) values ('Gert Kira', NULL);
insert into authors (name, biography) values ('Clerc Djakovic', NULL);
insert into authors (name, biography) values ('Stacee Elsy', NULL);
insert into authors (name, biography) values ('Dorotea Bonhill', NULL);
insert into authors (name, biography) values ('Minni Bunney', NULL);
insert into authors (name, biography) values ('Berty Gandley', NULL);
insert into authors (name, biography) values ('Raynard Tesdale', NULL);
insert into authors (name, biography) values ('Joanna Hutfield', NULL);
insert into authors (name, biography) values ('Dannie Glidder', NULL);
insert into authors (name, biography) values ('Timmie Adshede', NULL);
insert into authors (name, biography) values ('Fernando Neads', NULL);
insert into authors (name, biography) values ('Teddy Guilliland', NULL);
insert into authors (name, biography) values ('Paloma Grebert', NULL);
insert into authors (name, biography) values ('Kristos Usher', NULL);
insert into authors (name, biography) values ('Darcey Rohmer', NULL);
insert into authors (name, biography) values ('Cristie Isacsson', NULL);
insert into authors (name, biography) values ('Lindsay Coutthart', NULL);
insert into authors (name, biography) values ('Helyn Schneidar', NULL);
insert into authors (name, biography) values ('Bette-ann Askem', NULL);
insert into authors (name, biography) values ('Dom Robuchon', NULL);

insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Drucie Goodbourn', 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Marcia Aggiss', 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Giovanni Bigg', 'extend strategic e-services', '$272.00', '$151.04');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Duffie Eynon', 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Anselma McKennan', 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Gert Kira', 'architect vertical ROI', '$282.54', '$102.61');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Clerc Djakovic', 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Stacee Elsy', 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Dorotea Bonhill', 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Minni Bunney', 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Berty Gandley', 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Raynard Tesdale', 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Joanna Hutfield', 'scale integrated architectures', '$257.66', '$32.97');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Dannie Glidder', 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Timmie Adshede', 'strategize B2B channels', '$232.27', '$44.83');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Fernando Neads', 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Teddy Guilliland', 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Paloma Grebert', 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Kristos Usher', 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Darcey Rohmer', 'target innovative paradigms', '$298.94', '$130.01');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Cristie Isacsson', 'generate open-source e-business', '$276.57', '$113.25');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Lindsay Coutthart', 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Helyn Schneidar', 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Bette-ann Askem', 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (authorId, title, priceOld, price) values (select id from authors where name = 'Dom Robuchon', 'facilitate efficient eyeballs', '$232.30', '$131.48');
