DROP TABLE IF EXISTS authors;

CREATE TABLE authors(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(250) NOT NULL,
biography CLOB DEFAULT NULL
);

DROP TABLE IF EXISTS books;

CREATE TABLE  books(
id INT AUTO_INCREMENT PRIMARY KEY,
authorId INT,
title VARCHAR(250) NOT NULL,
priceOld  VARCHAR(250) DEFAULT NULL,
price VARCHAR(250) DEFAULT NULL,

FOREIGN KEY (authorId) REFERENCES authors (id)
);
